server:
  port: 8888

login:
  github:
    client:
      id: 34d536913cf2d29794e9
    redirect:
      uri: http://localhost:8888/callback/github
      client_secret: 912aa300c735825852862678f222380cf079f974
    request:
      uri: https://github.com/login/oauth/authorize

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useSSL=false&serverTimezone=GMT
    username: xkboy
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true